# ENGR 1451/2451 — Weekly Assignment 8
**10 points**

This assignment focuses on three goals from Week 7 that were not emphasized in LE07: **experimental design**, **how sample size changes the precision of a sample mean**, and **using confidence intervals to plan a study**.

**Due:** See Canvas.

Complete the work directly in this notebook. Show your Python code and give brief written explanations where requested. Submit the completed notebook as directed in Canvas.

## What to hand in

Work this assignment with the **course tutor** in the class project. That is the AI help to use on this assignment, and it keeps the record for you — you do not write one yourself.

At the end of each working session, type **"make my record"** in the chat. Copy the block it produces and paste it into the **Session records** cell near the bottom of this notebook.

You do not have to finish in one sitting. To pick up later, start a new chat in the same project, say which assignment you are on and which problem you stopped at, and keep going. That session gives you its own block, which you paste under the previous one.

Records are not graded for correctness or for how much help you needed, and extra credit is given for a record that shows you attempted the problem. The code and the written answers still have to be yours.

## LE8-1. Study design and causal evidence (3 pts)

For each study, classify it as a **randomized controlled experiment**, **observational study**, or **historical-control study**.

**a.** An engineer has 60 comparable metal specimens. The specimens are randomly assigned to either a new heat treatment or the standard heat treatment. All specimens are tested on the same fatigue-testing machine using the same procedure.

**b.** A manufacturer introduces a redesigned bearing this year and compares its failure rate with failure records from the previous bearing design five years ago.

**c.** A hospital compares outcomes for patients who chose to receive a therapy with outcomes for patients who chose not to receive it.

Then answer:

1. Which study gives the strongest basis for a **causal** conclusion?
2. What does random assignment help protect against?
3. Suppose the person measuring fatigue life knows which treatment each specimen received. What additional design feature could reduce measurement bias?

Keep your response to about 5–6 sentences total.

**Answer:**

a. randomized controlled experiment
b. historical-control study
c. observational study
1. The third study is most likely to have a causal relationship. Patients who choose to receive a therapy may have health factors that can impact the effectiveness of the therapy.
2. Random assignment seeks to get rid of bias so no confounding factors can impact a treatment or control group. When participants or test specimens are grouped at random, there is less chance of members of a group having one or more things in common.
3. If there is another person conducting the experiment, one could ID the specimen and the other person could run the test so there is test blindness in the design. Also, the fatigue testing machine should be calibrated appropriately and specimens from each group should be tested, that is, for example, NOT doing all the standard heat treated ones before the new-treatement specimens.

## LE8-2. Sample size and the precision of a mean (4 pts)

The file `./data/nist_aluminum_fatigue_21000psi.csv` contains fatigue-life measurements for **101 aluminum specimens** tested at a maximum stress of 21,000 psi. Fatigue life is reported in **thousand cycles**.

Treat these 101 measurements as a **sample from a broader population of comparable specimens manufactured and tested under the same conditions**. The population mean $\mu$ and population SD $\sigma$ are unknown.

The setup cell below calculates the sample mean and sample SD. We will use the observed sample SD as an estimate of $\sigma$ when thinking about the precision of future sample means.

In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats

pd.set_option("display.precision", 4)

fatigue = pd.read_csv("./data/nist_aluminum_fatigue_21000psi.csv")
life = fatigue["fatigue_life_thousand_cycles"].to_numpy()

n_observed = len(life)
sample_mean = life.mean()
sample_sd = life.std(ddof=1)

print(f"n = {n_observed}")
print(f"sample mean = {sample_mean:.1f} thousand cycles")
print(f"sample SD = {sample_sd:.1f} thousand cycles")

n = 101
sample mean = 1400.9 thousand cycles
sample SD = 391.3 thousand cycles

### A. How sample size changes the SE (2.5 pts)

Use the current sample SD as a planning estimate of $\sigma$ .

For planned future sample sizes

```python
planned_n = np.array([25, 100, 400])
```

calculate the estimated standard error

$
\widehat{SE}(\bar X)=\frac{s}{\sqrt{n}}.
$

Create a DataFrame with columns:

- `n`
- `estimated_se`

Report SE in **thousand cycles**.

Then answer:

1. What happens to the SE each time the sample size is multiplied by 4?
2. Does increasing the sample size change the population mean being estimated, or only the precision of the estimate?

**Answer:**
1. As sample size increases, estimated SE decreases by a factor of 2.
2. The changing sample size changes only the precision of the estimate because the population mean is independent of sample groups that can be picked.

In [2]:
planned_n = np.array([25, 100, 400])

# Calculate the estimated SE for each planned sample size.
# Create and display a DataFrame with columns n and estimated_se.

# Your code here
estimated_se = sample_sd/np.sqrt(planned_n)
sample_change = pd.DataFrame({
    "n":planned_n,
    "estimated_se":estimated_se
})
display(sample_change)

     n  estimated_se
0   25       78.2648
1  100       39.1324
2  400       19.5662

### B. Normal approximation for a future sample mean (1.5 pts)

Assume future measurements are independent and come from the same stable production process. Use the current sample SD $s$ as an estimate of $\sigma$.

For future samples of size $n=25$ and $n=100$, approximate the probability that the sample mean will be within **100 thousand cycles** of the true population mean:

$
P\left(|\bar X-\mu|\leq100\right).
$

For each sample size:

1. estimate $SE(\bar X)=s/\sqrt{n}$;
2. convert 100 thousand cycles to standard units,
   $
   z=\frac{100}{SE};
   $
3. use the normal curve:
   ```python
   stats.norm.cdf(z) - stats.norm.cdf(-z)
   ```

Display the two probabilities as percentages.

In one sentence, explain why the larger sample size gives a higher probability even though $\mu $ is unknown.

**Answer:** 
A larger sample size decreases the standard error which decreases the tail area in the distribution.

In [3]:
sample_sizes = np.array([25, 100])

# Calculate estimated SE for each sample size.
for i in range(2):
    print(f"estimated standard error for n = {planned_n[i]} is {estimated_se[i]:.3f}")
# Convert +/-100 thousand cycles to z units.
z = 100/estimated_se
# Calculate P(-z <= Z <= z) for each sample size.
p = np.zeros(2)
#print(z)
for j in range(2):
#    print(stats.norm.cdf(z[j]))
#    print(stats.norm.cdf(-z[j]))       ###debugging....

    p[j] = stats.norm.cdf(z[j]) - stats.norm.cdf(-z[j])  #finds two probabilities for n = 25, 100 respectively
# Display the results as percentages.
#print(p)
for i in range(2):
    print(f"The probability that the sample mean will be within 100 thousand cycles "
          f"of the pop. mean for n = {sample_sizes[i]} is {100*p[i]:.2f} %")
# Your code here

estimated standard error for n = 25 is 78.265
estimated standard error for n = 100 is 39.132
The probability that the sample mean will be within 100 thousand cycles of the pop. mean for n = 25 is 79.86 %
The probability that the sample mean will be within 100 thousand cycles of the pop. mean for n = 100 is 98.94 %

## LE8-3. Planning sample size for a confidence interval (3 pts)

Suppose the fatigue-life measurements above are a **pilot sample** for a future study. Use `sample_sd` as a planning estimate of the unknown population SD.

The goal is a **95% confidence interval for the population mean** with a specified margin of error.

For a planned sample size $n$,

$
\text{margin of error}
=
t^*_{n-1}\frac{s}{\sqrt{n}}.
$

This extends the confidence-interval calculation from LE07: here the question is not *what interval do we get from one sample?* but rather *how many measurements should we plan to collect?*

In [4]:
candidate_n = np.arange(5, 501)

t_star = stats.t.ppf(0.975, df=candidate_n - 1)
estimated_se = sample_sd / np.sqrt(candidate_n)
margin_of_error = t_star * estimated_se

### A. Find a sample size using Student's $t$ (2 pts)

Using the arrays above, find the **smallest** sample size for which the estimated 95% margin of error is no more than:

1. **100 thousand cycles**
2. **50 thousand cycles**

Boolean indexing is one way to do this:

```python
candidate_n[margin_of_error <= target][0]
```

Display both required sample sizes.

Then answer: approximately what happens to the required sample size when the target margin of error is cut in half?

**Answer:**
With margin of error cut in half, the needed sample size increases by almost a factor of four, or by a lot. This is because sample size is inside a square root.

In [5]:
# Find the smallest candidate_n meeting each target margin of error.

# Your code here
target_margins = np.array([100,50])
sizes = np.zeros(2)   #make a float array so it can be used in the loop with the mask
for i in range(2):
    sizes[i] = candidate_n[margin_of_error <= target_margins[i]][0] #get only sample size with needed margin of error
sample_size = pd.DataFrame({
    "sample_size": sizes,
    "margin_of_error_thousand_cycles": target_margins
})
display(sample_size)

   sample_size  margin_of_error_thousand_cycles
0         62.0                              100
1        238.0                               50

### B. Compare with the large-sample normal shortcut (1 pt)

For a target margin of error of **100 thousand cycles**, repeat the calculation using

```python
z_star = stats.norm.ppf(0.975)
normal_margin_of_error = z_star * sample_sd / np.sqrt(candidate_n)
```

Find the smallest sample size from the normal approximation.

In 1–2 sentences, compare this result with the Student's $t$ result from part A. Why is the $t$-based requirement slightly more conservative when $\sigma $ is unknown?

**Answer:**
t distribution, which was designed for smaller sample sizes, takes account for the degrees of freedom which causes the distribution to differ from the normal one. It increases the normal smallest size of 59 specimens to 62, which is only slightly more. This matches up with the fact for large sample sizes, norm can be used instead of t.

In [6]:
z_star = stats.norm.ppf(0.975)

# Calculate the normal-approximation margin of error

# for every value in candidate_n.
# Find the smallest sample size giving margin of error <= 100.

# Your code here
normal_margin_of_error = z_star * sample_sd / np.sqrt(candidate_n)

smallest_sample_with_norm = candidate_n[normal_margin_of_error <= target_margins[0]][0]
print(f"The smallest sample using the normal approximation with the target margin of error {target_margins[0]}"
      f" is {smallest_sample_with_norm} specimens")

The smallest sample using the normal approximation with the target margin of error 100 is 59 specimens

## Session records

At the end of each working session, type **"make my record"** in the chat and paste the block it produces into the cell below. If you work across several sessions, paste each new block underneath the previous one.

Assignments are not graded for correctness or for how much help you needed, and extra credit is given for a record that shows you attempted the problem. They are read to find out which steps are hardest, and used to improve the course.

<!-- Paste your session record blocks in this cell, one after another. -->

*(session records go here)*
{
  "schema_version": "engr-tutor-export-2",
  "assignment": "WA8",
  "export_n": 1,
  "session_date": "2026-10-27",
  "messages": [
    {"i": 1, "who": "student", "text": "can you check question 1 : \"1. The third study is most likely to have a causal relationship. Patients who choose to receive a therapy may have health factors that can impact the effectiveness of the therapy.\n2. Random assignment seeks to get rid of causal factors so no confounding factors can impact a treatment or control group. Participants or test specimens are randomly assigned to groups to avoid likeness inside groups.\n3. If there is another person conducting the experiment, one could ID the specimen and the other person could run the test so there is test blindness in the design. Also, the fatigue testing machine should be calibrated appropriately and specimens from each group should be tested, that is, for example, NOT doing all the standard heat treated ones before the new-treatement specimens."},
    {"i": 2, "who": "tutor", "text": "Your answer to question 3 is on the right track, and your answer to question 1 needs another look. [trimmed] Q1: asked what study c's self-selection does to a causal conclusion and in which study chance decided who got which treatment. Q2: wording loose (\"get rid of causal factors\", \"avoid likeness inside groups\"); asked what could differ between groups if the engineer picked by hand. Q3: unaware tester is the right design feature; testing order interleaving is a separate idea about machine drift. Also noted: classifications of a, b, c missing from the draft, and length slightly over 5-6 sentences."},
    {"i": 3, "who": "student", "code": true, "text": "check q2.a ? \"planned_n = np.array([25, 100, 400])\n\n# Calculate the estimated SE for each planned sample size.\n# Create and display a DataFrame with columns n and estimated_se.\n\n# Your code here\nestimated_se = sample_sd/np.sqrt(planned_n)\nsample_change = pd.DataFrame({\n    \"sample_size\":planned_n,\n    \"estimated_standard_error_thousand_cycles\":estimated_se\n})\ndisplay(sample_change) ....with written answer \"1. As sample size increases, estimated SE decreases by a factor of 2.\n2. The changing sample size changes only the precision of the estimate because the population mean is independent of sample groups that can be picked."},
    {"i": 4, "who": "tutor", "text": "Your code does what the step asks, and the SE calculation is correct. [trimmed] Noted: column names should be exactly n and estimated_se per the prompt; heads-up that the LE8-3 starter cell reassigns estimated_se. Answer 1: asked to divide one SE by the one before it and check against the table, and noted the sentence does not mention the fourfold increase. Answer 2: right side (only precision changes), reasoning unclear; asked what mu is a property of and which number in the table changes with n."},
    {"i": 5, "who": "student", "code": true, "text": "for part b, not sure what's going wrong here \"sample_sizes = np.array([25, 100])\n\n# Calculate estimated SE for each sample size.\nfor i in range(2):\n    print(f\"estimated standard error for n = {planned_n[i]} is {estimated_se[i]:.3f}\")\n# Convert +/-100 thousand cycles to z units.\nz = 100/estimated_se\n# Calculate P(-z <= Z <= z) for each sample size.\np = np.array([0,0,0])\nprint(z)\nfor j in range(2):\n    print(stats.norm.cdf(z[j]))\n    print(stats.norm.cdf(-z[j]))\n\n    p[j] = stats.norm.cdf(z[j]) - stats.norm.cdf(-z[j])\n# Display the results as percentages.\nprint(p*100000)\n# Your code here"},
    {"i": 6, "who": "tutor", "text": "Thanks for pasting the whole cell. [trimmed] Pointed out: loop uses planned_n and estimated_se from part A instead of sample_sizes; np.array([0,0,0]) is an integer array that truncates floats (use floats such as np.zeros(2), or skip the loop since the cdf expression works on whole arrays); percentages are multiplication by 100, not 100000; f\"{p:.1%}\" formatting note. Suggested next move: define the SE from sample_sd and sample_sizes and check that 100 / se has two entries. Offered the release valve."},
    {"i": 7, "who": "student", "text": "i got 79.86 % and 98.93%"},
    {"i": 8, "who": "tutor", "text": "Those match what I get from the project copy: 79.86% and 98.93% (to two decimals). [trimmed] Asked which code produced them, reminded that the prompt asks for the probabilities displayed as percentages, and that the one-sentence explanation is still needed; gave guiding questions (what is the probability a probability of, what happens to the spread of X-bar as n grows)."},
    {"i": 9, "who": "student", "code": true, "text": "can you check for q3.a \"targets = np.array([100,50])\nsizes = np.array([0,0])\nfor i in range(2):\n    sizes[i] = candidate_n[margin_of_error <= targets[i]][0]\nsample_size = pd.DataFrame({\n    \"sample_size\": sizes,\n    \"margin_of_error_thousand_cycles\": targets\n})\ndisplay(sample_size) ....and written answer \"With margin of error cut in half, the needed sample size increases by almost a factor of four, or by a lot."},
    {"i": 10, "who": "tutor", "text": "Your selection logic is right. [trimmed] It matches the project copy for both targets; both sizes displayed. Noted the targets column holds targets, not computed margins, and column names are the student's choice here. Written answer: points the right way but asked the student to divide the larger size by the smaller, replace \"or by a lot\" with what the numbers say, and think about why the margin depends on s/sqrt(n)."},
    {"i": 11, "who": "student", "text": "for b i got 59 specimens and I said \"t distribution, which was designed for smaller sample sizes, takes account for the degrees of freedom which causes the distribution to differ from the normal one."},
    {"i": 12, "who": "tutor", "text": "59 matches what I get from the project copy. [trimmed] Written answer: the comparison with part A's size and the gap are missing; the \"why\" stops short, so asked which of t* and z* is larger at these sizes and what the t distribution allows for when sigma is replaced by s; noted \"designed for smaller sample sizes\" is only partly right and asked whether the correction still matters at these sizes. Offered a toy example of t* versus df."},
    {"i": 13, "who": "student", "text": "could i do q3 a without the loop"},
    {"i": 14, "who": "tutor", "text": "Yes. A loop is one valid way to do it, and the selection itself doesn't need one. [trimmed] Explained that the selection works with a single target number, so it can be written once per target; comparing the margin array against an array of targets raises a shape ValueError; gave a generic example on unrelated data; noted the loop version is already correct."},
    {"i": 15, "who": "student", "text": "make my record"}
  ],
  "events": [
    {"i": 3, "part": "8-2A", "type": "code"},
    {"i": 5, "part": "8-2B", "type": "code"},
    {"i": 9, "part": "8-3A", "type": "code"},
    {"i": 13, "part": "8-3A", "type": "explain"}
  ],
  "parts": [
    {"part": "8-1", "exchanges": 1, "max_tier": 2, "passed": false},
    {"part": "8-2A", "exchanges": 1, "max_tier": 2, "passed": false},
    {"part": "8-2B", "exchanges": 2, "max_tier": 3, "passed": false},
    {"part": "8-3A", "exchanges": 2, "max_tier": 1, "passed": false},
    {"part": "8-3B", "exchanges": 1, "max_tier": 2, "passed": false}
  ],
  "tutor_assessment": [
    "The longest sticking point was LE8-2B: the student's cell reused part A's arrays (planned_n, estimated_se), stored probabilities in an integer array, and multiplied by 100000, before reaching the correct 79.86% and 98.93%. Written answers were also a recurring difficulty: LE8-1 question 1 (wrongly chose study c) and the loose wording of question 2, the LE8-2A answers (not matching the student's own SE ratio), and the LE8-3B comparison (missing the sizes and gap).",
    "No unstuck or release-valve use occurred in this session, so nothing looked like a tutoring failure. At the end of the session the written answers for LE8-1, LE8-2A, LE8-2B, LE8-3A and LE8-3B were still being revised, and the LE8-2B sentence had not yet been drafted."
  ]
}

## Before you submit

1. Confirm that the provided dataset is available at `./data/nist_aluminum_fatigue_21000psi.csv`.
2. **Restart Kernel and Run All Cells** and confirm every completed cell runs without errors.
3. Confirm your printed values and written answers are visible in the saved file.
4. Confirm your session record blocks are pasted into the cell above.
5. Save the notebook, then upload the `.ipynb` to Canvas.